apiVersion: v1
kind: ConfigMap
metadata:
  name: shiptrack-config
  namespace: shiptrack-pro
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: shiptrack-secrets
  namespace: shiptrack-pro
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_prod_password"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
